name: Integration Continue

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pylint-json2html
      - name: Analysing the code with pylint
        run: |
          pwd
          ls
          mkdir ./app/reports/pylint/report.json
          pylint $(git ls-files '*.py') > /app/reports/pylint/report.json; pylint-json2html -o /app/reports/pylint/report.html /app/reports/pylint/report.json || exit 0
  unittest-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install html-testRunner
      - name: Analysing the code with unittest
        run: |
          python -m unittest $(git ls-files 'test.py')

  run-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: start flask app
        run: |
          flask --app=./app/main.py run --host=0.0.0.0 &
          sleep 5

  robot-test:
    runs-on: ubuntu-latest
    needs: run-app
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      # - name: Robot Framework
      #   uses: joonvena/robotframework-docker-action@v1.1
      #   with:
      #     robot_tests_dir: app/test/system
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask

      - name: start flask app
        run: |
          flask --app=./app/main.py run --host=0.0.0.0 &
          sleep 5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-requests
          pip install robotframework-browser
          pip install flask
      - name: Analysing the code with robotframework
        run: |
          robot app/test/system/machine.robot

  # radon-test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version: ["3.8", "3.9", "3.10"]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install radon
  #         pip install json2tree
  #     - name: Analysing the code with radon
  #       run: |
  #         radon raw -j ../../app > reports/raw/report.json; json2tree -j reports/raw/report.json -o reports/raw/report.html -t 1
